title: "The Hub"
description: "My GitHub Pages site"
baseurl: ""
url: "https://fred-lim.github.io"
theme: jekyll-theme-midnight
markdown: kramdown
mathjax: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag